wp-erp/wp-erp

- composer.json
- composer.lock
- modules/hrm/assets/js/leave.js
- modules/hrm/includes/class-ajax.php
- modules/hrm/views/leave/holiday.php
This feature is able to import holidays from iCal files from the calendar services like Google Calendar. Try one of these ical files from Google Calendar:
https://calendar.google.com/calendar/ical/en.bd%23holiday%40group.v.calendar.google.com/public/basic.ics
https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics
> Add iCalendar import feature

- includes/class-install.php
- includes/framework/modules.php
> Fix 'Management' spelling error for module description

- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-hr-log.php
- modules/hrm/includes/functions-employee.php
HRM employee log done in 9 section:
employee : update, delete and create
In General Tab : work experience 2 operation [add, delete]
In General Tab : education 2 operation [add, delete]
In General Tab : dependents 2 operation [add, delete]
In Job Tab : employment status 2 operation [add, delete]
In Job Tab : compensation 2 operation [add, delete]
In Job Tab : job information 2 operation [add, delete]
> HRM employee log done

- composer.lock
- includes/functions-company.php
- modules/hrm/includes/class-form-handler.php
> Add new Leave Entitlements for multiple employees fixed

- includes/class-countries.php
- modules/hrm/views/js-templates/new-employee.php
Add new employee form field nationality has no default value
> Fixed new employee nationality field default value issue

- modules/crm/includes/class-contact-forms-integration.php
Change people meta source value from dynamic value to static option.
> Change contact forms integration source value

- modules/crm/includes/class-contact-list-table.php
> crm contacts order by fix

- includes/functions-people.php
- modules/crm/assets/js/crm.js
- modules/crm/includes/class-ajax.php
- modules/crm/includes/class-contact.php
- modules/crm/views/company/single.php
- modules/crm/views/contact/single.php
- modules/crm/views/js-templates/new-customer.php
Default source fields:
- Advertisement
- Chat
- Contact Form
- Employee Referral
- External Referral
- Marketing campaign
- Newsletter
- OnlineStore
- Optin Forms
- Partner
- Phone Call
- Public Relations
- Sales Mail Alias
- Search Engine
- Seminar-Internal
- Seminar Partner
- Social Media
- Trade Show
- Web Download
- Web Research
> Add Feature: CRM contact birth date and contact source fields

- assets/js/erp.js
- includes/admin/class-audit-list-table.php
- includes/admin/models/audit-log.php
- includes/class-log.php
1) Added date filter
2) 'Created at' column is now showing the time properly.
> Audit log filter

- modules/hrm/includes/actions-filters.php
the callback function was removed earlier, that's why the error came.
> fixed error: removed people type callback from hr module

- modules/accounting/accounting.php
In accounting module, need to add a do action that accounting module is loaded. It will be helpful for accounting's add-ons.
> added accouting module loaded action

- modules/accounting/includes/class-admin-menu.php
- modules/accounting/includes/views/expense/transaction-list.php
for future use of dependency add-on, put filter for sales transaction template and put action for sales transaction action.
>  put filter for sales transaction template and put action for sales transaction action

- includes/functions-html.php
> Added some file types in file_upload option

- modules/accounting/includes/views/pdf/invoice.php
- modules/accounting/includes/views/pdf/payment.php
- modules/accounting/includes/views/sales/invoice-single.php
- modules/accounting/includes/views/sales/payment-single.php
Changed the title to "Description" from "Product" in Invoice/Payment
& Added description for each sale/product in the invoice/payment fixed #441
> updated invoice & payment

- modules/hrm/includes/emails/class-email-approved-leave-request.php
- modules/hrm/includes/emails/class-email-new-leave-request.php
- modules/hrm/includes/emails/class-email-rejected-leave-request.php
- modules/hrm/includes/models/Employee_Note.php
- modules/hrm/includes/models/Hr_User.php
- modules/hrm/includes/models/announcement.php
- modules/hrm/includes/models/designation.php
- modules/hrm/includes/models/employee.php
- modules/hrm/includes/models/leave-entitlement.php
- modules/hrm/includes/models/leave-holiday.php
- modules/hrm/includes/models/leave-policies.php
- modules/hrm/includes/models/leave-request.php
- modules/hrm/includes/models/leave.php
- modules/hrm/includes/models/performance.php
Nothing actually useful, but I am a cleanliness freak. 😅 
Please let me know if I did anything wrong, as this is my first ever pull request in my life. Just started with
git. 😅
> Template names in comments corrected

- modules/hrm/includes/class-ajax.php
This fixes #453 - by saving the Leave request reject reason first into table column and then calling the email function
> Fixes #453

- modules/accounting/includes/views/pdf/payment.php
- modules/accounting/includes/views/sales/payment-single.php
> Removed due date from the payment

- i18n/states/SA.php
I have added support to Saudi Arabia regions.
Saudi regions in English from Wikipedia:
https://en.wikipedia.org/wiki/Regions_of_Saudi_Arabia
Saudi regions in Arabic from Wikipedia:
https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D8%A6%D9%85%D8%A9_%D8%A7%D9%84%D9%85%D9%86%D8%A7%D8%B7%D9%82_%D8%A7%D9%84%D8%A5%D8%AF%D8%A7%D8%B1%D9%8A%D8%A9_%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9
> add support for Saudi Arabia regions (states)

- modules/hrm/views/leave/leave-entitlements.php
help text with link to adding new leave policy when there is none. it will help users to create leave policy easily.
> Added help text for leave policy option

- modules/hrm/includes/class-announcement.php
- modules/hrm/includes/functions-announcement.php
* Add by departments and by designations option for sending/create an announcement.
#33
> Add by departments and by designations option to create an announcement

- includes/functions-people.php
- modules/accounting/includes/actions-filters.php
- modules/accounting/includes/class-settings.php
- modules/accounting/includes/functions.php
Feature Request Added: Import CRM users into accounting module
#394
> Fixes #394

- README.md
> Available Addons section updated

- modules/accounting/includes/class-journal-transactions-list-table.php
- modules/accounting/includes/views/expense/vendor-credit-single.php
- modules/crm/includes/functions-customer.php
> Updated some spelling mistakes 

- modules/accounting/includes/functions.php
- modules/crm/includes/functions-customer.php
Create accounting customer from wordpress user
#394
> Create accounting customer from wp user

- includes/functions-people.php
> Fixes #540 The search function is not working on accounting customers and vendors list page

- modules/accounting/includes/class-ajax.php
- modules/accounting/includes/functions-transaction.php
- modules/accounting/includes/functions.php
- modules/accounting/includes/views/sales/payment-single.php
> fixes #552

- includes/api/class-announcements-controller.php
- modules/hrm/includes/functions-reporting.php
- modules/hrm/views/employee.php
Fixed HRM gender reporting count error.
> fixes #565

- assets/css/admin.css
- assets/less/admin/admin.less
- includes/api/class-departments-controller.php
- includes/api/class-designations-controller.php
- includes/api/class-employees-controller.php
- modules/hrm/includes/functions-department.php
- modules/hrm/includes/functions-designation.php
- package-lock.json
> Employee and department API search

- modules/hrm/includes/functions-department.php
> Fixes #661

- modules/accounting/assets/js/erp-accounting.js
- modules/accounting/includes/class-form-handler.php
>  Invoice total price should not be zero

- assets/css/admin.css
- includes/functions-html.php
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/functions-employee.php
- modules/hrm/views/js-templates/new-employee.php
> Field added by custom field builder is not aligned properly

- modules/hrm/includes/api/class-employees-controller.php
> Unable to terminate an employee

- includes/admin/views/tools/import.php
- includes/functions.php
- modules/accounting/includes/views/common/transaction-chart.php
- modules/hrm/includes/api/class-employees-controller.php
- modules/hrm/includes/class-employee.php
> Expense chart information updated

- modules/hrm/includes/class-employee.php
> Rejected leave request hide from leave calendar

- includes/functions.php
> fixed employee export issue

- modules/crm/includes/functions-customer.php
- modules/hrm/includes/api/class-employees-controller.php
- modules/hrm/includes/class-leave-request-list-table.php
- modules/hrm/includes/functions-leave.php
> New employee login details api added

- includes/framework/class-settings-page.php
- includes/framework/modules.php
- modules/hrm/includes/functions-reporting.php
- modules/hrm/includes/models/employee.php
>  Fixes #655 & #697

- modules/hrm/includes/class-announcement.php
> Pass selected employees on announcement save hook

- modules/hrm/includes/api/class-announcements-controller.php
- modules/hrm/includes/api/class-leave-holidays-controller.php
> Fixed some missing argument issues in leave rest api endpoints

- modules/hrm/includes/api/class-employees-controller.php
> Fix: Note api update

- includes/admin/class-menu.php
- modules/hrm/includes/admin/class-menu.php
- modules/hrm/includes/class-announcement-list-table.php
- modules/hrm/includes/functions-employee.php
> add hrm menu structure

- includes/api/class-rest-controller.php
> change links in rest response according to wp style

- assets/css/admin.css
- assets/less/admin/admin.less
- includes/admin/class-menu.php
- includes/functions.php
> Header menu and admin bar menu styles updated

- assets/css/admin.css
- assets/less/admin/admin.less
> Update secondary header menu design

- assets/css/admin.css
- assets/less/admin/admin.less
> admin bar submenu menu and secondary header menu design

- modules/hrm/includes/functions-employee.php
- modules/hrm/views/employee/single.php
> Fixes #727

- includes/functions-people.php
- modules/hrm/includes/api/class-employees-controller.php
> Fix leave request email from api

- modules/hrm/includes/admin/class-menu.php
- modules/hrm/includes/api/class-employees-controller.php
> Fix menu highlighting issue

- modules/accounting/assets/less/core/common.less
- modules/accounting/assets/less/core/variables.less
- modules/accounting/assets/less/elements/forms.less
- modules/accounting/assets/less/elements/panel.less
- modules/accounting/assets/src/admin/components/Dashboard.vue
> fix dashboard ui issues

- modules/accounting/assets/less/elements/buttons.less
- modules/accounting/assets/less/elements/forms.less
- modules/accounting/assets/less/elements/table.less
- modules/accounting/assets/src/admin/components/tax/NewTaxModal.vue
- modules/accounting/assets/src/admin/components/tax/TaxRates.vue
> added new tax modal

- modules/hrm/includes/functions-reporting.php
- modules/hrm/views/reporting/age-profile.php
- modules/hrm/views/reporting/headcount.php
> Fix employee age profile report

- modules/hrm/includes/functions-reporting.php
- modules/hrm/views/reporting/salary-history.php
> Fix employee salary history report

- modules/crm/views/js-templates/customer-email-note.php
> Fixed the Attachment button label

- modules/accounting/assets/src/admin/components/people/EmployeeDetails.vue
- modules/accounting/assets/src/admin/components/people/Employees.vue
- modules/accounting/assets/src/admin/components/people/PeopleTransaction.vue
- modules/accounting/assets/src/admin/components/transactions/sales/SalesStats.vue
- modules/accounting/assets/src/admin/router/index.js
> New accounting

- includes/functions-people.php
- modules/crm/includes/class-ajax.php
- modules/crm/includes/functions-customer.php
- modules/crm/views/reports/customer-report.php
- modules/hrm/assets/js/leave.js
- modules/hrm/includes/class-leave-report-employee.php
- modules/hrm/includes/functions-leave.php
> Fix contact list view and edit for crm agent

- modules/accounting/assets/src/admin/components/modal/Modal.vue
- modules/accounting/assets/src/admin/components/people/People.vue
- modules/accounting/assets/src/admin/components/people/PeopleModal.vue
- modules/accounting/assets/src/admin/components/transactions/sales/SalesSingle.vue
> Added mail modal in sales single page

- modules/hrm/includes/class-employee-list-table.php
> Add filter for employee row actions

- assets/css/admin.css
- assets/less/admin/admin.less
- includes/functions.php
> Fix modal style

- modules/accounting/includes/classes/class-admin.php
> Make people from employee

- modules/accounting/assets/js/erp-accounting.js
- modules/accounting/includes/class-admin-menu.php
> Fix vendor country state

- modules/accounting/assets/src/admin/components/chart-accounts/ChartOfAccounts.vue
- modules/accounting/assets/src/admin/components/reports/IncomeStatement.vue
> Fix chart of account table column alignment

- i18n/states/PT.php
- includes/class-countries.php
> Portugal states are missing

- modules/crm/includes/class-contact-group-list-table.php
- modules/crm/includes/class-form-handler.php
> CRM Agents can delete the contact group

- modules/accounting/includes/views/vendor/single.php
- modules/crm/includes/actions-filters.php
- modules/crm/includes/class-emails.php
- modules/crm/includes/emails/class-email-birthday-greetings.php
- modules/crm/includes/functions-customer.php
- modules/crm/views/activities.php
> Send birthday greetings to contacts

- modules/hrm/includes/class-form-handler.php
> Fix: saving leave entitlement redirects to leave requests #820

- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-form-handler.php
- modules/hrm/views/js-templates/new-leave-request.php
- modules/hrm/views/leave/new-request.php
Fixed -- Leave reason field is required now .
> Leave reason field is made required now

- modules/crm/includes/functions-customer.php
CRM email template variable tag doesn't work . This issue is fixed .
> Fixed CRM mail template issue

- modules/hrm/includes/functions-dashboard-widgets.php
> Remove button to send birthday email to employees from HR dashboard

- includes/functions.php
The Mega Menu Items for Accounting needs to have the #
#870
> WP ERP Accounting Mega Menu items need to be compatible with Vue

- includes/updates/bp/class-erp-acct-bg-process-1.5.0.php
- includes/updates/update-1.5.0.php
> replace `Ledger_Map::getInstance` with `Ledger_Map::get_instance`

- assets/css/admin.css
- includes/actions-filters.php
- includes/class-email.php
- includes/class-emailer.php
- includes/functions.php
- modules/crm/assets/js/crm-contacts.js
- modules/crm/assets/js/crm.js
- modules/crm/includes/admin/class-settings.php
- modules/crm/includes/functions-customer.php
- modules/crm/views/schedules.php
- modules/hrm/includes/functions-dashboard-widgets.php
- modules/hrm/includes/functions-employee.php
- modules/hrm/includes/functions.php
> Enhancement of weekly digest email

- includes/functions.php
> Fixed import issues for unicode character

- modules/crm/includes/class-subscription-widget.php
- modules/crm/includes/functions-dashboard.php
- modules/crm/views/js-templates/customer-add-schedules.php
- modules/crm/views/js-templates/customer-log-activity.php
- modules/crm/views/js-templates/customer-schedule-note.php
- modules/crm/views/js-templates/customer-tasks-note.php
- modules/crm/views/js-templates/single-schedule-details.php
- modules/hrm/views/js-templates/new-dept.php
file: modules/crm/includes/functions-dashboard.php 
Line no:  166 and 170 
Removed wp_kses_post due to data attribute, data-schedule_id doesn’t work, data-scheduled and data-schedule-id works
we need to apply different approach here, instead of applying whole string as a single wp_kese_post argument, we need to divide it to multiple parts.
> fixed github issue #949

- includes/functions-people.php
- includes/functions.php
> fixed import issues caused via wrongly called sanitize functions.

- modules/crm/includes/functions-dashboard.php
> fixed formatting issue on CRM - Dashboard - Today's Schedule section

- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-policies.php
- includes/updates/update-1.5.15.php
- modules/hrm/includes/functions-leave.php
> started working on leave_management branch

- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-entitlements.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-policies.php
- includes/updates/update-1.5.15.php
> data migration: leave entitlements and leave policies tables

- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-entitlements.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-policies.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-request.php
- includes/updates/update-1.5.15.php
> added chained migration process

- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-entitlements.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-policies.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-request.php
- includes/updates/update-1.5.15.php
> fixed data migration issues

- modules/hrm/includes/class-leave-request-list-table.php
- modules/hrm/includes/functions-dashboard-widgets.php
- modules/hrm/includes/functions-leave.php
- modules/hrm/includes/functions.php
- modules/hrm/views/leave/calendar.php
> sprint sp-2026 - first week changes

- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-request.php
- includes/updates/update-1.5.15.php
- modules/hrm/includes/class-form-handler.php
> sprint sp-2026 - second week changes - fixed missing db fields

- modules/crm/views/activities.php
- modules/crm/views/contact/feeds.php
> Added hook after feed content

- includes/class-addon-task.php
- includes/functions.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-entitlements.php
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/functions-dashboard-widgets.php
- modules/hrm/includes/functions-leave.php
- modules/hrm/includes/functions.php
- modules/hrm/includes/models/financial-year.php
- modules/hrm/includes/models/leave-approval-status.php
- modules/hrm/includes/models/leave-encashment-request.php
- modules/hrm/includes/models/leave-entitlement.php
- modules/hrm/includes/models/leave-policies-segregation.php
- modules/hrm/includes/models/leave-policies.php
- modules/hrm/includes/models/leave-request-detail.php
- modules/hrm/includes/models/leave-request.php
- modules/hrm/includes/models/leave-unpaid.php
- modules/hrm/includes/models/leave.php
- modules/hrm/views/js-templates/new-leave-request.php
- modules/hrm/views/leave/calendar.php
- modules/hrm/views/leave/new-request.php
- modules/hrm/views/settings/fyear.php
> Leave management

- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-entitlements-list-table.php
- modules/hrm/includes/class-leave-request-list-table.php
- modules/hrm/includes/functions-dashboard-widgets.php
- modules/hrm/views/employee/tab-leave-history.php
- modules/hrm/views/employee/tab-leave.php
> sprint sp-2026 - fixed half day view (morning/evening)

- includes/class-updates.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-entitlements.php
- includes/updates/bp/leave_1_5_15/class-erp-hr-leave-request.php
- modules/hrm/includes/functions-leave.php
> updated leave policy query

- modules/hrm/includes/functions-leave.php
- modules/hrm/includes/models/leave-policies.php
> fixed policy delete task

- README.md
> Update installation procedure

- modules/hrm/includes/functions-leave.php
> fixed error string

- modules/hrm/includes/functions-dashboard-widgets.php
> changed icon for next month who is out leaves

- modules/hrm/includes/functions-leave.php
> added filter for employee type while adding entitlement

- includes/admin/views/erp-overview.php
> Checked channel data availability

- modules/crm/includes/functions-customer.php
> Fixes #1061

- modules/hrm/includes/class-form-handler.php
> Fixed leave bulk action issue

- modules/hrm/includes/class-form-handler.php
> Enhance leave request bulk action field sanitizations

- composer.json
- composer.lock
- includes/admin/views/tools/import.php
- includes/class-updates.php
- includes/class-validate-data.php
- includes/functions.php
- includes/updates/update-1.6.5.php
- wp-erp.php
> Import export csv validation

- modules/hrm/includes/functions-leave.php
> Added title,start & end date filter at holidays csv import

- modules/hrm/includes/api/class-departments-controller.php
- modules/hrm/includes/api/class-employees-controller.php
- modules/hrm/includes/functions-department.php
> Crm hrm api

- modules/crm/views/import-user-to-crm.php
- modules/hrm/assets/js/leave.js
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-entitlements-list-table.php
- modules/hrm/includes/class-form-handler.php
- modules/hrm/includes/class-leave-request-list-table.php
- modules/hrm/includes/class-policy-list-table.php
- modules/hrm/includes/functions-leave.php
- modules/hrm/includes/models/leave-policies.php
- modules/hrm/includes/models/leave-request.php
- modules/hrm/views/leave/leave-entitlements.php
- modules/hrm/views/leave/new-policy.php
> Employee type leave filter

- includes/class-install.php
- includes/class-validate-data.php
- includes/email/email-body.php
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/functions-dashboard-widgets.php
> Version 1.6.7 updates

- modules/crm/includes/class-ajax.php
- modules/crm/includes/functions-customer.php
Added segment filtering for inactive contacts/company with befor, after, and in between date option.
> Inactive contact segmentation

- includes/class-validate-data.php
- includes/functions.php
> Updated export import permission

- includes/functions-people.php
- includes/functions.php
- modules/hrm/includes/class-employee.php
- Fixed name and city validation issues
> Fixed name and city validation issues

- modules/hrm/includes/class-employee.php
> update employee display name when update employe info

- modules/hrm/includes/functions-employee.php
[update] Updated delete employee function to remove all leave related reference on employee force delete
> Updated delete employee to delete all leave refers

- includes/class-promotion.php
> Added promotional text for 2020

- modules/crm/includes/contact-forms/class-contact-forms-integration.php
- modules/crm/includes/contact-forms/class-erp-settings-contact-forms.php
Fixed crm contact owner gets reset every time a user submit a contact form #1077
> Fixed git issue #1077

- includes/admin/class-setup-wizard.php
[new] Added wemail marketing step in setup wizard
> Added weMail section in install wizard

- modules/hrm/includes/class-employee.php
- modules/hrm/includes/functions-employee.php
[new] Added action for employee after update status
> Employee sync attendance

- modules/hrm/includes/class-employee-list-table.php
[fix] Fixed employee search problem issue
> Fixed employee search problem in other languages #1128

- includes/functions-people.php
- modules/crm/assets/js/crm-contacts.js
- modules/crm/includes/admin/class-menu.php
- modules/crm/views/company/single.php
- modules/crm/views/contact/single.php
[fix] Fixed type checking issue for contact-company
[new] Added restriction to edit trashed contacts
> Fixed contact type checking issue #711

- includes/class-promotion.php
> Add holiday promotion for 2020

- modules/hrm/includes/class-employee.php
Updated action hook for update employee status
> Updated employee status update action hook

- modules/hrm/includes/class-employee.php
> Fixed permission issue for frontend

- modules/crm/includes/functions-capabilities.php
> Fixed crm agent contact edit issue

- modules/hrm/includes/class-employee.php
- modules/hrm/includes/functions-employee.php
> Fixed employee check

- modules/hrm/includes/class-form-handler.php
> Fixed nonce verification issue while leave year is being saved

- modules/hrm/includes/class-employee.php
- modules/hrm/includes/class-hr-log.php
> fix - Custom Field Add/Update Issue on save employee

- assets/js/erp.js
- includes/functions-html.php
- modules/accounting/assets/src/admin/components/people/PeopleModal.vue
- modules/crm/assets/js/crm-contacts.js
- modules/hrm/assets/js/hrm.js
- modules/hrm/includes/class-employee.php
- modules/hrm/includes/class-hr-log.php
> Fix: Custom Field Builder Issues

- includes/functions-people.php
- includes/functions.php
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-employee.php
- modules/hrm/includes/functions-employee.php
- modules/hrm/views/js-templates/employee-terminate.php
- modules/hrm/views/js-templates/employment-status.php
[fix] Existing employees were unable to update upon reaching user limit
[fix] Direct termination was not updating employee history
[fix] Some minor undefined index issues on employee related actions
[update] Some datepicker autocomplete in forms has been prevented
[update] User limit check has been applied on employee status update and restore
[update] Sanitization on all phone number input has been applied. From now on, only numeric characters and optionally '+' at the beginning will be saved.
> Fixed user limit was being applied to update employee as well

- assets/js/erp.js
- modules/accounting/api/class-rest-api-transactions.php
- modules/accounting/assets/src/admin/components/base/Datepicker.vue
- modules/accounting/assets/src/admin/components/reports/LedgerReport.vue
- modules/accounting/assets/src/admin/components/transactions/DynamicTrnLoader.vue
- modules/accounting/assets/src/admin/components/transactions/TransactionsFilter.vue
- modules/accounting/assets/src/admin/components/transactions/expenses/ExpensesList.vue
- modules/accounting/assets/src/admin/components/transactions/purchases/PurchasesList.vue
- modules/accounting/assets/src/admin/components/transactions/sales/SalesList.vue
- modules/accounting/includes/classes/class-assets.php
- modules/accounting/includes/functions/reports.php
- modules/accounting/includes/functions/transactions.php
- modules/crm/assets/js/vue-table.js
- modules/crm/views/contact.php
- modules/hrm/assets/js/hrm.js
- modules/hrm/includes/class-employee-list-table.php
- modules/hrm/views/employee.php
[fix] Date filtering was not working for expense transaction
[fix] Inconsistent end date on ledger reports filters
[fix] Some components were not loading properly
> Fixed accounting expense related issues

- modules/accounting/api/class-rest-api-tax-rate-names.php
- modules/accounting/assets/src/admin/components/tax/RecordPayTax.vue
- modules/accounting/assets/src/admin/components/tax/TaxRateLineAdd.vue
- modules/accounting/assets/src/admin/components/tax/TaxRateLineEdit.vue
- modules/accounting/assets/src/admin/components/tax/TaxRateRow.vue
- modules/accounting/assets/src/admin/components/tax/TaxRecords.vue
[fix] Tax rates were unable to update
[update] Temporarily disabled actions on tax payments
[update] updated design of tax rate forms
> Fixed taxes were unable to update

- modules/crm/views/company/feeds.php
- modules/crm/views/contact/feeds.php
[fix] Auto complete issues for Date picker.
> fix #1147 - Remove auto complete on select date

- assets/less/admin/crm.less
- modules/crm/assets/css/email-attachment.css
- modules/crm/assets/js/crm-app.js
- modules/crm/assets/js/crm-components.js
- modules/crm/includes/class-ajax.php
- modules/crm/includes/functions-customer.php
- modules/crm/views/js-templates/customer-email-note.php
- modules/crm/views/js-templates/customer-log-activity.php
- modules/crm/views/js-templates/customer-newnote.php
- modules/crm/views/js-templates/customer-schedule-note.php
- modules/crm/views/js-templates/customer-tasks-note.php
- modules/crm/views/js-templates/timeline-email.php
- modules/crm/views/js-templates/timeline-log-activity.php
- modules/crm/views/js-templates/timeline-new-note.php
- modules/crm/views/js-templates/timeline-task.php
> Added attachment feature for all section on CRM contacts

- modules/crm/assets/js/vue-table.js
- modules/crm/views/company.php
[fix] CRM modules Contact and company filter issue resolved after merge.
> Fixed CRM Filter

- assets/css/admin.css
- assets/less/admin/admin.less
- modules/hrm/assets/js/hrm.js
- modules/hrm/views/js-templates/new-employee.php
[update] Add New Create Button of Department and Designation on Employee create
> Add Create New Button for Department & Designation on create Employee

- modules/accounting/includes/classes/class-admin.php
- modules/accounting/includes/functions/bills.php
- modules/accounting/includes/functions/capabilities.php
- modules/accounting/includes/functions/expenses.php
- modules/accounting/includes/functions/invoices.php
- modules/accounting/includes/functions/journals.php
- modules/accounting/includes/functions/pay-purchases.php
- modules/accounting/includes/functions/products.php
- modules/accounting/includes/functions/purchases.php
- modules/accounting/includes/functions/rec-payments.php
- modules/accounting/includes/functions/taxes.php
- modules/accounting/includes/functions/transactions.php
- [fix] Big select and strict mode issues on accounting
- [fix] Accounting manager permission checkbox option was not showing in employee permissions tab
> Fix: Accounting issues

- modules/hrm/includes/class-form-handler.php
- modules/hrm/includes/class-hr-log.php
- modules/hrm/includes/class-policy-list-table.php
- modules/hrm/views/leave/leave-entitlements.php
> Updated filtering usecase while creating leave entitlement

- modules/crm/includes/class-google-auth.php
[fix] Error regarding gmail api connection with CRM when google auth generates error
> Fixed fatal error while connecting gmail api with crm

- includes/class-promotion.php
> Limited time summer sale offer notice

- includes/admin/class-ajax.php
- includes/class-validate-data.php
- includes/functions.php
- modules/accounting/api/class-rest-api-products.php
- modules/accounting/assets/src/admin/components/people/ExportModal.vue
- modules/accounting/assets/src/admin/components/people/ImportModal.vue
- modules/accounting/assets/src/admin/components/products/ExportModal.vue
- modules/accounting/assets/src/admin/components/products/ImportModal.vue
- modules/accounting/assets/src/admin/components/products/ProductModal.vue
- modules/accounting/assets/src/admin/components/products/Products.vue
- modules/accounting/assets/src/admin/components/products/Search.vue
- modules/accounting/includes/classes/class-admin.php
- modules/accounting/includes/classes/class-assets.php
- modules/accounting/includes/functions/products.php
- modules/crm/views/js-templates/customer-import.php
- modules/hrm/views/js-templates/employee-import.php
> Products import/Export

- assets/less/admin/hrm.less
- modules/hrm/assets/js/hrm.js
- modules/hrm/assets/less/hrm.less
- modules/hrm/hrm.php
- modules/hrm/includes/class-ajax.php
- modules/hrm/includes/class-employee-list-table.php
- modules/hrm/includes/class-employee.php
- modules/hrm/views/employee/tab-job.php
- modules/hrm/views/js-templates/compensation-history-edit.php
- modules/hrm/views/js-templates/compensation.php
- modules/hrm/views/js-templates/employee-terminate.php
- modules/hrm/views/js-templates/employment-status.php
- modules/hrm/views/js-templates/employment-type-history-edit.php
- modules/hrm/views/js-templates/employment-type.php
- modules/hrm/views/js-templates/job-info-history-edit.php
- modules/hrm/views/js-templates/job-info.php
- [update] Current history of employment type, compensation, and job info will be able to be edited
- [update] In the employee list table, instead of 'Status' a new column will show the status update date for non active status filters
- [update] Some optimization to make the performance better
- [fix] Existing data were not parsing properly while updating job related information of employees
- [fix] Current job history in the employee section was not showing properly in some cases
> Enhancement: Employee list page and single page

- includes/admin/class-ajax.php
- includes/settings/includes/Helpers.php
- modules/accounting/includes/classes/Accounting_Tutorial.php
[fix] Fixed some conflicts and improve codes.
> Fix Some conflicts and Code Improve

- assets/less/admin/crm.less
- modules/crm/assets/js/vue-table.js
[fix] Fixed CRM Contact table responsive issue
[fix] Fixed CRM Company table responsive issue
> Fix CRM - Contact and Company table responsive issues

- modules/hrm/views/employee/tab-general.php
- [update] Meta postbox design of employee single page
- [fix] Termination widget was not showing in employee single page
> Update: metabox design in employee single page

- includes/functions.php
- modules/crm/includes/emails/class-email-new-task-assigned.php
[enhance] Added task description and link in Email while sending Email notifications to users after creating task.
> Add More Data and Link on CRM Task Creating Email

- includes/admin/class-form-handler.php
- includes/admin/class-menu.php
- includes/admin/views/tools/general.php
- includes/functions.php
- modules/hrm/includes/functions-leave.php
- wp-erp.php
- [enhance] Added Support for dynamic side menu list hiding option from Tools General Section
- [enhance] Added some more admin toolbar options to hide in Tools General Section
- [fix] Fixed text-domain to `erp` for some text
- [fix] Converted Department Leads Eloquent query to $wpdb to fix some conflict
> Side Menubar and Toolbar Menu list Hiding Enhancement

- includes/functions.php
- modules/crm/views/reports/growth-report.php
[fix] CRM Growth report labels were not translatable
> Added translation support in growth report

- includes/class-promotion.php
- [notice] Limited time promotional offer regarding Black Friday and Cyber Monday
> Added offer notice for black friday

- assets/css/invoice-front.css
- includes/class-updates.php
- includes/updates/update-1.10.2.php
- modules/accounting/assets/src/admin/components/transactions/sales/InvoiceSingleContent.vue
- modules/accounting/includes/views/transactions/invoice-readonly.php
- Enhancement: Invoice Attachment Download Links added in Publicly available invoice link.
- Enhancement: Invoice Attachment Download Links added in Print Media mode
> Enhancement: Invoice Attachment Download Links in Print Mode or Invoice Link

- includes/Settings/assets/src/components/crm/contact-forms/CrmContactForm.vue
- includes/Settings/assets/src/components/layouts/BaseContentLayout.vue
- [fix] CRM settings were not saved properly
> Fix: CRM settings issues

- includes/class-promotion.php
- modules/hrm/includes/class-employee-list-table.php
> Notice: Christmas promotion

- includes/functions-people.php
- modules/accounting/includes/functions/common.php
- modules/crm/assets/js/crm-contacts.js
- modules/crm/crm.php
- modules/crm/includes/class-ajax.php
- modules/crm/includes/functions-customer.php
- Enhanced convert option from Accounting customer to CRM Contacts (vice versa)
- Fixed some data redundancy
> Fixed double entry of people in accounting on auto import

- includes/framework/modules.php
[**fix**] wrong module name passed to action hook 'erp_module_after_deactivated'
> fixed wrong module name passed to action hook 'erp_module_after_deactivated'

- includes/Settings/Email.php
- includes/admin/class-ajax.php
- includes/class-promotion.php
- includes/framework/modules.php
- includes/functions-cache-helper.php
- includes/functions-people.php
- includes/functions.php
- modules/accounting/includes/functions/common.php
- modules/accounting/includes/functions/transactions.php
- modules/crm/assets/js/crm-contacts.js
- modules/crm/crm.php
- modules/crm/includes/class-ajax.php
- modules/crm/includes/functions-customer.php
- modules/hrm/includes/class-employee-list-table.php
> Sync version1.10.3

- includes/Settings/Ajax.php
- modules/accounting/api/class-rest-api-taxes.php
- modules/accounting/assets/src/admin/components/people/Employees.vue
- modules/crm/includes/class-ajax.php
> Fixed some minor issues

- includes/Settings/assets/src/components/layouts/BaseLayout.vue
- **fix:** Fixed undefined title and description issues on base layout
> Fix: Fixed some random issues for overall plugin

- includes/class-scripts.php
- includes/functions.php
- [fix] Resetting ERP was deleting admin user in some cases
> Fix: ERP reset issues

- includes/functions-people.php
> fix/checked if CRM module is active inside `erp_get_peoples` function

- modules/hrm/views/reporting/leave.php
This will fix ERP PRO's [this issue.](https://github.com/wp-erp/erp-pro/issues/155)
> Fix Filter value gets removed when going to next page on Leave Report

- assets/css/admin.css
- modules/hrm/assets/js/leave.js
- modules/hrm/includes/LeaveRequestsListTable.php
- wp-erp.php
This will fix ERP PRO's [this issue.](https://github.com/wp-erp/erp-pro/issues/153)
> Fix Keep values in leave request filter.

- modules/accounting/includes/functions/common.php
This will fix [this issue](https://github.com/wp-erp/erp-pro/issues/157)
> Fix Contacts are not importing properly

- includes/Settings/Helpers.php
🛠️ [FIX] Settings -> Integration -> Mailchimp Configure -> PHP Notice:  Undefined index: type wp-content/plugins/erp/includes/Settings/Helpers.php on line 215
> 🛠️ [FIX] Settings -> Integration -> Mailchimp Configure -> PHP Notice

- includes/functions.php
This will [fix](https://github.com/wp-erp/erp-pro/issues/80) this issue.
> 🛠️ [FIX] If no mail setup in WP ERP, then sent mail with default wp

- includes/Admin/views/modules.php
This will fix [this issue](https://github.com/wp-erp/erp-pro/issues/83)
> 🛠️ [FIX] Redirects on the purchased extensions while activating/deactivating on module page.

- includes/Admin/AdminMenu.php
This will close [this issue.](https://github.com/wp-erp/erp-pro/issues/150)
> 🔥 [NEW] Add Create Invoice Button to Accounting Sidebar Menu.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> 🪝 [ADD] issue templates

- .github/ISSUE_TEMPLATE/bug_report.yml
> 🪝 [ADD] System Info

- .github/ISSUE_TEMPLATE/bug_report.yml
> 🛠️ [FIX] issue template

- modules/hrm/views/employee/tab-general.php
Fixes [#171](https://github.com/wp-erp/erp-pro/issues/171)
> 🛠️ [FIX] Dependents DOB empty - Showing random date.

- modules/hrm/assets/js/hrm.js
Fixes [#172](https://github.com/wp-erp/erp-pro/issues/172)
> 🛠️ [FIX] Employee Notes - Not adding the notes given properly.

- assets/css/admin.css
- assets/less/admin/admin.less
Fixes [#180](https://github.com/wp-erp/erp-pro/issues/180)
Fixes [#1416](https://github.com/wp-erp/wp-erp/issues/1416)
> Fix Menu items overlapping

- includes/WeDevsERPInstaller.php
- modules/accounting/includes/Emails/TransactionalEmail.php
- modules/accounting/includes/Emails/TransactionalEmailEstimate.php
- modules/accounting/includes/Emails/TransactionalEmailPayPurchase.php
- modules/accounting/includes/Emails/TransactionalEmailPayments.php
- modules/accounting/includes/Emails/TransactionalEmailPurchase.php
- modules/accounting/includes/Emails/TransactionalEmailPurchaseOrder.php
[#176](https://github.com/wp-erp/erp-pro/issues/176)
> 🛠️ [FIX] Invoice ID is not showing for Sales Transaction

- assets/css/customs.css
- modules/hrm/assets/js/hrm.js
- modules/hrm/views/employee.php
[#143](https://github.com/wp-erp/erp-pro/issues/143)
> 🪝 [ADD] Implement Live Search on People

- modules/accounting/assets/src/admin/components/people/Employees.vue
Fixes [#179](https://github.com/wp-erp/erp-pro/issues/179)
> 🛠️ [FIX] Redirecting to incorrect page instead of Profile.

- modules/crm/includes/ContactForms/NinjaForms.php
Fixes [#185](https://github.com/wp-erp/erp-pro/issues/185)
> 🛠️ [FIX] Ninja Forms integration error

- includes/Admin/AdminMenu.php
- includes/Admin/views/modules.php
- modules/accounting/assets/src/admin/components/invoice/InvoiceCreate.vue
This will fix-
* If accounting module is active, then add Create the Invoice menu.
* Display none code block for Trix editor.
* Module page sorting issues.
> 🛠️ [FIX] previous release issues.

- assets/js/erp.js
- includes/Lib/WeFormsUpsell.php
- modules/accounting/Accounting.php
[#181](https://github.com/wp-erp/erp-pro/issues/181)
> Fix security vulnerability on notices

- includes/Updates.php
- includes/Updates/update-1.12.7.php
- modules/hrm/assets/js/hrm.js
> 🔥 For 1.12.7 release fix

- includes/Updates.php
- includes/Updates/update-1.12.7.php
- modules/crm/includes/functions-customer.php
- modules/hrm/assets/js/hrm.js
> Fix CRM contact list count error

- includes/Admin/AuditlogListTable.php
- modules/crm/includes/ContactGroupListTable.php
- modules/hrm/includes/DepartmentListTable.php
- modules/hrm/includes/DesignationListTable.php
- modules/hrm/includes/EntitlementListTable.php
- modules/hrm/includes/LeavePoliciesListTable.php
- modules/hrm/views/leave/holiday.php
This will fix WP List Table error
> 🛠️ [FIX] WP List Table error

- modules/accounting/assets/src/admin/components/pay-purchase/PayPurchaseCreate.vue
Updated the markup  closing tag `</tbody>` to fix the UI.
Issue: https://github.com/wp-erp/erp-pro/issues/204
> UI Breakdown in Purchases > Pay Purchase #204 Fix UI in  Pay Purchase

- modules/accounting/assets/src/admin/components/purchase/PurchaseCreate.vue
- Fix Remove attachment issue for create purchase
> Fix remove attachment issue for create purchase

- modules/hrm/includes/FormHandler.php
[Related issue](https://wedevs.slack.com/archives/C12G7P9MJ/p1702853941648709)
> 🛠️ [FIX] Segregation leave policy

- modules/hrm/includes/FormHandler.php
Reverts wp-erp/wp-erp#1449
The logic applied here is not working as expected and does not fulfill the requirement that satisfy Leave-Segregation rule.
> Revert "🛠️ [FIX] Segregation leave policy"

- composer.json
- composer.lock
- includes/Settings/Email.php
- modules/crm/includes/functions-customer.php
- package.json
- wp-erp.php
> 🛠️ [FIX] google api client for org release

- composer.json
- composer.lock
- includes/Settings/Email.php
- modules/crm/includes/functions-customer.php
- wp-erp.php
> Revert "🛠️ [FIX] google api client for org release"

- composer.json
- composer.lock
Appsesro composer package updated to v2.0.4
> Fix: Translation loaded to early

- modules/hrm/includes/functions-leave.php
fixes [250](https://github.com/wp-erp/erp-pro/issues/250)
The issue of ordering leave is fixed
> fix order by filter

- includes/Admin/SetupWizard.php
Update SetupWizard.php
Fixed string echo in SetupWizard.php
> Fixed string echo in SetupWizard.php

- includes/ValidateData.php
- modules/hrm/includes/AjaxHandler.php
Fixed issues with string translations
> Fixed issues with string translations

- includes/Admin/Ajax.php
fixes [#278](https://github.com/wp-erp/erp-pro/issues/278)
> Fix: Unauthorized user delete location

- modules/crm/CRM.php
- modules/hrm/HRM.php
> Fix: CLI file include error

- includes/Item.php
- includes/People.php
> Fixed CRM contacts attribute data missing

- modules/crm/includes/AjaxHandler.php
Fixes : #1502
HTML Email note and preview is fixed in this pr.
> Fix : HTML preview and email note
