wp-erp/wp-erp

- includes/functions.php
If given date is before 1970-01-01 or null then it will show a dash from now on.
> Fix format for the dates before epoch time

- includes/class-settings.php
- wp-erp.php
There is no less file for it and no reference in Gruntfile.js.
This commit removes a 404 css error in ERP Settings page.
> Remove settings.css from enqueuing

- includes/class-install.php
Now all modules in ERP Settings > Modules can be disabled. And if all of them are disabled, wp-erp will throw a fatal error on plugin re-activation. This issue is fixed.
> Fix plugin re-activation fatal error

- modules/hrm/includes/functions-employee.php
Tried to fix #451 
Added the code to check if the current logged in user role is **Employee**.
If yes, then the URL will contain page=erp-my-profile.
If not, then the URL will contain page=erp-hr-employee.
Please modify the code if it feels sloppy, would like to see if there's a better way to do this.
> Employee tabs URL changed to erp-my-profile - Tried to fix #451

- modules/crm/includes/functions-customer.php
ERP Settings >> CRM if auto import is enabled and we are making wp user from contact the newly created user will recreate another contact in addition to original one as "erp_crm_make_wp_user" function is calling "wp_insert_user" function which do "user_register" action which is the hook of "erp_create_contact_from_created_user" function. and so a new contact is created.
Another conflict is that the "erp_create_contact_from_created_user" function does not pass (first_name, last_name, email) to "erp_insert_people" function so the created contact data is empty and it also affects the creation of new users in WordPress.
> Fix: create contact from created user conflicts

- modules/crm/includes/functions-customer.php
Add module activation check before calling the function.
#544
> Fixes #544 When Accounting module is deactivated, gives a fatal error.

- modules/crm/includes/functions-customer.php
the function 'erp_crm_update_contact_owner' is passed two
parameters: contact_id, owner_id. the contact_id seems to refer to
the 'user_id' field in the wp_erp_peoples table, however, the function
implementation is populating the contact object with the 'id' field
of the wp_erp_peoples table.
lookup contact by user_id, grab id field, use id field to construct the Contact object.
see issue #746
> fix issue: update contact owner by user_id

- includes/updates/bp/class-erp-acct-bg-process-1.5.0.php
Otherwise, at the invoice page, the discount would be applied twice. Once at the conversion script here, and the second at the Invoice page screen.
..._erp_acct_invoice_details.line_total shall not have any discount subtracted from it.
#852
> ..._erp_acct_invoice_details.line_total should not contain any discount.

- modules/accounting/assets/src/admin/components/purchase/PurchaseRow.vue
..._erp_acct_purchase_details.price is decimal(10,2) in the database.
If step is not set to 0.01, the unit price field can only accept integer values.
#867
> Unit Price needs to be able to accept decimal values.

- modules/hrm/includes/class-announcement.php
- modules/hrm/includes/functions-announcement.php
https://github.com/wp-erp/wp-erp/issues/905
> Fixed - Can't send SMS if all employees are selected

- assets/css/admin.css
- assets/less/admin/admin.less
- includes/functions-people.php
- includes/functions.php
- modules/crm/views/js-templates/new-customer.php
1. Current contact import system will work if any of the first_name or phone or email fields data are present. but this doesn't ensure unique contact entry on the database. If a user only provides the first_name field, the current CSV import feature treats each new submission as a new entry. Also, we can't add validation for first_name because this field is not unique. In the source, email is checked for duplicate entry, so I added the first_name and email field as required.   
2. Fixed a small CSS issue.
> added first_name and email as required fields to avoid duplicate entry

- modules/accounting/includes/functions/reports.php
Wrong Dr/Cr label is showing at the rightmost balance column in the list row of accounting ledger details report page.
> Fixed balance of ledger report debit-credit label

- modules/crm/assets/js/crm-app.js
- modules/crm/views/contact/feeds.php
On CRM Contact Activity Feeds Filter once a filter is used added an option to remove a filter and display all activities again.
The filtering option on the Activities Timeline in CRM Contact Profile didn't have an option to bring back the timeline of all activities once any of the filters were used.
The only solution to once again see the full list of activities was to refresh the page.
None that I'm aware of.
> CRM Contact Activity Feeds Filter - display All activities

- modules/accounting/includes/functions/transactions.php
[**enhance**] replaced `&nbsp;` with space for input to the erp-pdf-invoice
part of [this](https://github.com/wp-erp/erp-pdf-invoice/pull/19)
> replaced `&nbsp;` with space for input to the erp-pdf-invoice

- modules/crm/includes/contact-forms/class-contact-forms-integration.php
say, gravity-form field id 12, 13, 44 etc maps to same contact field 'street_2', then if gravity-form field 12 has value but others are empty and the sequence of execution is 12, 13, 44 then the value in contact['street_2'] set by gravity-form field 12 was being overridden by gravity-form field 13 and 44. Now we have checked if `contact[ $field ]` is already filled to prevent override.
> fixed empty value field problem if multiple gravity-form field map to same contact field

- modules/crm/includes/class-ajax.php
fix for Text format not persisting on Contacts > Contact Details > Notes, Log activity, Schedule, Tasks section
- [fix] Text formats were not persisting while creating different activities for a contact/company (CRM)
> fix/email formatting doesn't persist for crm contacts

- includes/functions.php
- modules/accounting/assets/src/admin/components/menu/AccountingMenu.vue
- modules/accounting/includes/Classes/Admin.php
🛠️ [FIX] ERP Help button displaying.
🔨 [REFACTOR] erp_is_valid_zip_code() {3,8} to {3,12}
This will close [this issue](https://github.com/wp-erp/erp-pro/issues/160).
> 🛠️ [FIX] ERP Help button displaying.

- includes/functions.php
🛠️ [FIX] After updating a CRM Contact and/or Company, the user got Debug log Error:
PHP Notice:  Undefined index: type in wp-content/plugins/erp/includes/functions.php on line 3412
PHP Notice:  Undefined index: photo_id in wp-content/plugins/erp/includes/functions.php on line 3412
> 🛠️ [FIX] Undefined index when updating a CRM Contact and/or a Company.

- includes/functions-people.php
🛠️ [FIX] Fatal error on debug log when creating a vendor from the accounting module.
PHP Notice:  Undefined variable: type_obj in wp-content/plugins/wp-erp/includes/functions-people.php on line 699
> 🛠️ [FIX] Fatal error on debug log when creating a vendor

- modules/hrm/assets/js/hrm.js
- modules/hrm/includes/LeaveRequestsListTable.php
- Enable `Reset` option for leave requests filter.
- Fix: Filter by status not working
- https://github.com/wp-erp/erp-pro/issues/169
- https://github.com/wp-erp/erp-pro/issues/227
> Enable reset option for leave filter

- includes/Settings/Ajax.php
Remove text field sanitization to get the setting fields. Because 
- There is no write  operation in database.
- There are some the fields like `desc` which we need a HTML data.
> Remove sanitizer to get the setting fields

- composer.json
- composer.lock
- Remove the `illuminate/database` package duplicacy since it is already required in `tareq1988/wp-eloquent`.
- Change the version for `wp-coding-standards/wpcs` package to `dev-develop` for **PHP** version 7.4
- Ran `composer update` command to change the `composer.lock` file.
I removed `illuminate/database` package comparing the commit https://github.com/wp-erp/wp-erp/commit/5afe4edbdc6bc4fe534c28010d4c959048d69342.
> Remove illuminate/database package duplicacy

- modules/hrm/views/employee/single.php
fixes [#266](https://github.com/wp-erp/erp-pro/issues/266)
Terminated employee data can't be viewed by other employee who didn't have access.
> Fix: Unauthorized Access to Terminated Employee Information

- modules/accounting/includes/API/InvoicesController.php
fixes [#265](https://github.com/wp-erp/erp-pro/issues/265)
The WP ERP plugin version 1.13.3 contains a stored XSS vulnerability. This issue allows administrators to execute Cross-Site Scripting (XSS) attacks, which is a low-risk issue but can have significant implications on WordPress Multisite configurations.
> Fix: Admin+ Stored XSS Vulnerability

- modules/hrm/includes/actions-filters.php
- modules/hrm/includes/functions-employee.php
I've added intercept functionality when the admin try to delete User or bulk user.
If they have linked employee account it will prevent and notice for this action.
fixed #1504
> check and Intercept if user has employee if tried to delete

- modules/hrm/includes/functions-department.php
https://github.com/wp-erp/erp-pro/issues/298
After creating a new department, the old cache is not cleared.
> Fixed: Department cache issue
